/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Mar 17, 2010, 10:32:50 AM
 */
package swing;

import java.awt.event.ActionEvent;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultButtonModel;
import model.CmnModel;
import java.lang.reflect.*;

/**
 *
 * @author konne
 */
public class CmnSwingFrame extends javax.swing.JFrame {
    private Method _set;
    private Method _is;
    private CmnModel _model;

    private class CheckBoxModel extends DefaultButtonModel {
        CheckBoxModel(String property) {
            try {
                _property = property;
                _is = _model.getClass().getMethod("is" + _property);
                _set = _model.getClass().getMethod("set" + _property, boolean.class);
            } catch (NoSuchMethodException ex) {
                Logger.getLogger(CmnSwingFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SecurityException ex) {
                Logger.getLogger(CmnSwingFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        @Override
        public boolean isSelected() {
            try {
                return (Boolean) _is.invoke(_model);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(CmnSwingFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvocationTargetException ex) {
                Logger.getLogger(CmnSwingFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            return false;
        }

        @Override
        public void setPressed(boolean b) {
            if (b) {
                try {
                    _set.invoke(_model,!isSelected());
                } catch (SecurityException ex) {
                    Logger.getLogger(CmnSwingFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(CmnSwingFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalArgumentException ex) {
                    Logger.getLogger(CmnSwingFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InvocationTargetException ex) {
                    Logger.getLogger(CmnSwingFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

        private String _property;
    }

    /** Creates new form MainFrame */
    public CmnSwingFrame(CmnModel model) {
        _model = model;
        initComponents();

        // connect gui to model for all checkboxes
        jClearIndexCheckBox.setModel(new CheckBoxModel("ClearIndex"));
        jCreateLibraryCheckBox.setModel(new CheckBoxModel("CreateLibrary"));
        jCreateMergeOverviewCheckBox.setModel(new CheckBoxModel("CreateMergeOverview"));
        jCreateUnplayableFileOverviewCheckBox.setModel(new CheckBoxModel("CreateUnplayableFileOverview"));
        jGenerateMd5CheckBox.setModel(new CheckBoxModel("GenerateMd5"));
        jGenerateFingerprintCheckBox.setModel(new CheckBoxModel("GenerateFingerprint"));
        jGenerateFilenameTagsCheckBox.setModel(new CheckBoxModel("GenerateFilenameTags"));
        jGenerateFoldernameTagsCheckBox.setModel(new CheckBoxModel("GenerateFoldernameTags"));
        jObtainPuidCheckBox.setModel(new CheckBoxModel("ObtainPuid"));
        jObtainId3TagsCheckBox.setModel(new CheckBoxModel("ObtainId3Tags"));
        jObtainMusicidTagsCheckBox.setModel(new CheckBoxModel("ObtainMusicidTags"));
        jObtainMusicbrainzTagsCheckBox.setModel(new CheckBoxModel("ObtainMusicbrainzTags"));
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jClearIndexCheckBox = new javax.swing.JCheckBox();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jGenerateMd5CheckBox = new javax.swing.JCheckBox();
        jGenerateFilenameTagsCheckBox = new javax.swing.JCheckBox();
        jGenerateFoldernameTagsCheckBox = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        jGenerateFingerprintCheckBox = new javax.swing.JCheckBox();
        jObtainId3TagsCheckBox = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        jObtainPuidCheckBox = new javax.swing.JCheckBox();
        jObtainMusicidTagsCheckBox = new javax.swing.JCheckBox();
        jObtainMusicbrainzTagsCheckBox = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jCreateLibraryCheckBox = new javax.swing.JCheckBox();
        jCreateMergeOverviewCheckBox = new javax.swing.JCheckBox();
        jCreateUnplayableFileOverviewCheckBox = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setBorder(null);

        jPanel3.setBorder(null);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Database Index"));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jButton6.setText("Create Database");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel10.add(jButton6, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel10.add(jComboBox1, gridBagConstraints);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel10.add(jTextField2, gridBagConstraints);

        jClearIndexCheckBox.setText("Clear index content before indexing");
        jClearIndexCheckBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jClearIndexCheckBoxPropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel10.add(jClearIndexCheckBox, gridBagConstraints);

        jPasswordField1.setText("jPasswordField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel10.add(jPasswordField1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel10.add(jSeparator2, gridBagConstraints);

        jLabel5.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel10.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel10.add(jLabel6, gridBagConstraints);

        jPanel3.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Sources"));
        jPanel11.setLayout(new java.awt.GridBagLayout());

        jButton2.setText("Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel11.add(jButton2, gridBagConstraints);

        jButton1.setText("Add");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel11.add(jButton1, gridBagConstraints);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel11.add(jScrollPane1, gridBagConstraints);

        jPanel3.add(jPanel11, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Index", jPanel3);

        jPanel7.setLayout(new java.awt.GridLayout(0, 1));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Files"));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));

        jGenerateMd5CheckBox.setText("Generate Md5 Hash");
        jPanel12.add(jGenerateMd5CheckBox);

        jGenerateFilenameTagsCheckBox.setText("Generate Tags from Filename");
        jPanel12.add(jGenerateFilenameTagsCheckBox);

        jGenerateFoldernameTagsCheckBox.setText("Generate Tags from Foldernames");
        jGenerateFoldernameTagsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGenerateFoldernameTagsCheckBoxActionPerformed(evt);
            }
        });
        jPanel12.add(jGenerateFoldernameTagsCheckBox);

        jPanel7.add(jPanel12);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Music Files"));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.Y_AXIS));

        jGenerateFingerprintCheckBox.setText("Generate Fingerprint");
        jPanel13.add(jGenerateFingerprintCheckBox);

        jObtainId3TagsCheckBox.setText("Obtain ID3 Tags");
        jPanel13.add(jObtainId3TagsCheckBox);

        jPanel7.add(jPanel13);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Online Services"));
        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.Y_AXIS));

        jObtainPuidCheckBox.setText("Obtain Puid from MusicId");
        jPanel14.add(jObtainPuidCheckBox);

        jObtainMusicidTagsCheckBox.setText("Obtain Tags from MusicId");
        jPanel14.add(jObtainMusicidTagsCheckBox);

        jObtainMusicbrainzTagsCheckBox.setText("Obtain Tags from MusicBrainz");
        jObtainMusicbrainzTagsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jObtainMusicbrainzTagsCheckBoxActionPerformed(evt);
            }
        });
        jPanel14.add(jObtainMusicbrainzTagsCheckBox);

        jPanel7.add(jPanel14);

        jTabbedPane1.addTab("Analyser", jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("File naming"));
        jPanel8.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Song Merging"));
        jPanel15.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html> Songs need to be extremly similar in order to be considered the same. </html><html>  Wrong merges are very unlikly but finding all similar songs is almost impossible. </html>");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 17));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 500));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        jPanel15.add(jLabel1, gridBagConstraints);
        jLabel1.getAccessibleContext().setAccessibleName("<html>\nSongs need to be extremly<p>\nsimilar in order to be<p>\nconsidered the same.<p>\nWrong merges are very<p>\nunlikly but finding all similar<p>\nsongs is almost impossible.\n</html>");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html> Finding many douplicate songs is likly, but it is also possible that songs will be mistaken to be the same even if they are not.</html>");
        jLabel2.setMinimumSize(new java.awt.Dimension(200, 500));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        jPanel15.add(jLabel2, gridBagConstraints);

        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setMaximumSize(new java.awt.Dimension(200, 48));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel15.add(jSlider1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        jPanel15.add(jLayeredPane1, gridBagConstraints);

        jLabel7.setText("<html> Even remotly similar songs are considered to be the same. </html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel15.add(jLabel7, gridBagConstraints);

        jLabel8.setText("<html> Even remotly similar songs are considered to be the same. </html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel15.add(jLabel8, gridBagConstraints);

        jPanel8.add(jPanel15, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Filter", jPanel8);

        jPanel9.setBorder(null);
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Destination"));
        jPanel17.setLayout(new java.awt.GridBagLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jPanel17.add(jTextField1, gridBagConstraints);

        jButton7.setText("...");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        jPanel17.add(jButton7, gridBagConstraints);

        jCreateLibraryCheckBox.setText("Create library");
        jCreateLibraryCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateLibraryCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel17.add(jCreateLibraryCheckBox, gridBagConstraints);

        jCreateMergeOverviewCheckBox.setText("Create merge overview");
        jCreateMergeOverviewCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateMergeOverviewCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel17.add(jCreateMergeOverviewCheckBox, gridBagConstraints);

        jCreateUnplayableFileOverviewCheckBox.setText("Create unplayable file overview");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel17.add(jCreateUnplayableFileOverviewCheckBox, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        jPanel17.add(jSeparator3, gridBagConstraints);

        jPanel9.add(jPanel17);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Library Naming Scheme"));
        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setText("In order to create a template describing how songs will be stored in the music libarary, drag Elements from this box");
        jPanel16.add(jLabel4);

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jScrollPane2.setViewportView(jList2);

        jPanel16.add(jScrollPane2);

        jLabel3.setText("...into this one, , that will be applied to store songs in the music library");
        jPanel16.add(jLabel3);

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList3.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jScrollPane3.setViewportView(jList3);

        jPanel16.add(jScrollPane3);

        jPanel9.add(jPanel16);

        jTabbedPane1.addTab("Library", jPanel9);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(jSeparator1, gridBagConstraints);

        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel4.add(jButton3, gridBagConstraints);

        jButton5.setText("Previous");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel4.add(jButton5, gridBagConstraints);

        jButton4.setText("Cancel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.weightx = 1.0;
        jPanel4.add(jButton4, gridBagConstraints);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCreateMergeOverviewCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateMergeOverviewCheckBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jCreateMergeOverviewCheckBoxActionPerformed

    private void jCreateLibraryCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateLibraryCheckBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jCreateLibraryCheckBoxActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

    private void jObtainMusicbrainzTagsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jObtainMusicbrainzTagsCheckBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jObtainMusicbrainzTagsCheckBoxActionPerformed

    private void jGenerateFoldernameTagsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGenerateFoldernameTagsCheckBoxActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jGenerateFoldernameTagsCheckBoxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

    private void jClearIndexCheckBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jClearIndexCheckBoxPropertyChange
        System.out.println(evt.getPropertyName());
//        _model.setClearIndex((Boolean));
    }//GEN-LAST:event_jClearIndexCheckBoxPropertyChange

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            _model.writeXml();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CmnSwingFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jClearIndexCheckBox;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JCheckBox jCreateLibraryCheckBox;
    private javax.swing.JCheckBox jCreateMergeOverviewCheckBox;
    private javax.swing.JCheckBox jCreateUnplayableFileOverviewCheckBox;
    private javax.swing.JCheckBox jGenerateFilenameTagsCheckBox;
    private javax.swing.JCheckBox jGenerateFingerprintCheckBox;
    private javax.swing.JCheckBox jGenerateFoldernameTagsCheckBox;
    private javax.swing.JCheckBox jGenerateMd5CheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JCheckBox jObtainId3TagsCheckBox;
    private javax.swing.JCheckBox jObtainMusicbrainzTagsCheckBox;
    private javax.swing.JCheckBox jObtainMusicidTagsCheckBox;
    private javax.swing.JCheckBox jObtainPuidCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
